In [1]:
import pandas as pd

In [2]:
calendar = pd.read_csv("../data/raw/calendar.csv")

In [3]:
calendar.head()

          version https://git-lfs.github.com/spec/v1
0                                       <<<<<<< HEAD
1  oid sha256:d12b5914ef03e66649adf5dd9e996e66022...
2                                        size 103469
3                                            =======
4  oid sha256:ca67ec6704084302882b8e97148abb174e7...

In [15]:
import pandas as pd

calendar = pd.read_csv("../data/raw/calendar.csv")

print(calendar.columns.tolist())

['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

In [16]:
import pandas as pd
calendar = pd.read_csv("../data/raw/calendar.csv")
print(calendar.columns.tolist())

['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

In [17]:
import pandas as pd

calendar = pd.read_csv("../data/raw/calendar.csv")

In [18]:
print(calendar.columns.tolist())

['date', 'wm_yr_wk', 'weekday', 'wday', 'month', 'year', 'd', 'event_name_1', 'event_type_1', 'event_name_2', 'event_type_2', 'snap_CA', 'snap_TX', 'snap_WI']

In [19]:
calendar["date"] = pd.to_datetime(calendar["date"])

calendar["year"] = calendar["date"].dt.year
calendar["month"] = calendar["date"].dt.month
calendar["week"] = calendar["date"].dt.isocalendar().week
calendar["day"] = calendar["date"].dt.day
calendar["weekday"] = calendar["date"].dt.day_name()

In [20]:
calendar["date"].head()

0   2011-01-29
1   2011-01-30
2   2011-01-31
3   2011-02-01
4   2011-02-02
Name: date, dtype: datetime64[ns]

In [21]:
calendar["date"].dtype

dtype('<M8[ns]')

In [22]:
calendar["date"] = pd.to_datetime(calendar["date"])

In [23]:
calendar["date"].dtype

dtype('<M8[ns]')

In [24]:
calendar["year"] = calendar["date"].dt.year

In [25]:
calendar[["date", "year"]].head()

        date  year
0 2011-01-29  2011
1 2011-01-30  2011
2 2011-01-31  2011
3 2011-02-01  2011
4 2011-02-02  2011

In [26]:
calendar["month"] = calendar["date"].dt.month

In [27]:
calendar[["date", "month"]].head()

        date  month
0 2011-01-29      1
1 2011-01-30      1
2 2011-01-31      1
3 2011-02-01      2
4 2011-02-02      2

In [28]:
calendar["week"] = calendar["date"].dt.isocalendar().week

In [29]:
calendar[["date", "week"]].head()

        date  week
0 2011-01-29     4
1 2011-01-30     4
2 2011-01-31     5
3 2011-02-01     5
4 2011-02-02     5

In [30]:
calendar["day"] = calendar["date"].dt.day

In [31]:
calendar[["date", "day"]].head()

        date  day
0 2011-01-29   29
1 2011-01-30   30
2 2011-01-31   31
3 2011-02-01    1
4 2011-02-02    2

In [32]:
calendar["weekday"] = calendar["date"].dt.day_name()

In [33]:
calendar[["date", "weekday"]].head()

        date    weekday
0 2011-01-29   Saturday
1 2011-01-30     Sunday
2 2011-01-31     Monday
3 2011-02-01    Tuesday
4 2011-02-02  Wednesday

In [34]:
calendar[[
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2"
]].head(20)

     event_name_1 event_type_1 event_name_2 event_type_2
0             NaN          NaN          NaN          NaN
1             NaN          NaN          NaN          NaN
2             NaN          NaN          NaN          NaN
3             NaN          NaN          NaN          NaN
4             NaN          NaN          NaN          NaN
5             NaN          NaN          NaN          NaN
6             NaN          NaN          NaN          NaN
7             NaN          NaN          NaN          NaN
8       SuperBowl     Sporting          NaN          NaN
9             NaN          NaN          NaN          NaN
10            NaN          NaN          NaN          NaN
11            NaN          NaN          NaN          NaN
12            NaN          NaN          NaN          NaN
13            NaN          NaN          NaN          NaN
14            NaN          NaN          NaN          NaN
15            NaN          NaN          NaN          NaN
16  ValentinesDay     Cultural          NaN          NaN
17            NaN          NaN          NaN          NaN
18            NaN          NaN          NaN          NaN
19            NaN          NaN          NaN          NaN

In [35]:
event_columns = [
    "event_name_1",
    "event_type_1",
    "event_name_2",
    "event_type_2"
]

calendar[event_columns] = calendar[event_columns].fillna("No Event")

In [36]:
calendar[event_columns].head(20)

     event_name_1 event_type_1 event_name_2 event_type_2
0        No Event     No Event     No Event     No Event
1        No Event     No Event     No Event     No Event
2        No Event     No Event     No Event     No Event
3        No Event     No Event     No Event     No Event
4        No Event     No Event     No Event     No Event
5        No Event     No Event     No Event     No Event
6        No Event     No Event     No Event     No Event
7        No Event     No Event     No Event     No Event
8       SuperBowl     Sporting     No Event     No Event
9        No Event     No Event     No Event     No Event
10       No Event     No Event     No Event     No Event
11       No Event     No Event     No Event     No Event
12       No Event     No Event     No Event     No Event
13       No Event     No Event     No Event     No Event
14       No Event     No Event     No Event     No Event
15       No Event     No Event     No Event     No Event
16  ValentinesDay     Cultural     No Event     No Event
17       No Event     No Event     No Event     No Event
18       No Event     No Event     No Event     No Event
19       No Event     No Event     No Event     No Event

In [37]:
calendar.head()

,date,wm_yr_wk,weekday,wday,month,year,d,event_name_1,event_type_1,event_name_2,event_type_2,snap_CA,snap_TX,snap_WI,week,day
0,2011-01-29,11101,Saturday,1,1,2011,d_1,No Event,No Event,No Event,No Event,0,0,0,4,29
1,2011-01-30,11101,Sunday,2,1,2011,d_2,No Event,No Event,No Event,No Event,0,0,0,4,30
2,2011-01-31,11101,Monday,3,1,2011,d_3,No Event,No Event,No Event,No Event,0,0,0,5,31
3,2011-02-01,11101,Tuesday,4,2,2011,d_4,No Event,No Event,No Event,No Event,1,1,0,5,1
4,2011-02-02,11101,Wednesday,5,2,2011,d_5,No Event,No Event,No Event,No Event,1,0,1,5,2

In [38]:
calendar[
    [
        "date",
        "year",
        "month",
        "week",
        "day",
        "weekday",
        "event_name_1",
        "event_type_1",
        "event_name_2",
        "event_type_2"
    ]
].head(10)

,date,year,month,week,day,weekday,event_name_1,event_type_1,event_name_2,event_type_2
0,2011-01-29,2011,1,4,29,Saturday,No Event,No Event,No Event,No Event
1,2011-01-30,2011,1,4,30,Sunday,No Event,No Event,No Event,No Event
2,2011-01-31,2011,1,5,31,Monday,No Event,No Event,No Event,No Event
3,2011-02-01,2011,2,5,1,Tuesday,No Event,No Event,No Event,No Event
4,2011-02-02,2011,2,5,2,Wednesday,No Event,No Event,No Event,No Event
5,2011-02-03,2011,2,5,3,Thursday,No Event,No Event,No Event,No Event
6,2011-02-04,2011,2,5,4,Friday,No Event,No Event,No Event,No Event
7,2011-02-05,2011,2,5,5,Saturday,No Event,No Event,No Event,No Event
8,2011-02-06,2011,2,5,6,Sunday,SuperBowl,Sporting,No Event,No Event
9,2011-02-07,2011,2,6,7,Monday,No Event,No Event,No Event,No Event

In [39]:
print("Start date:", calendar["date"].min())
print("End date:", calendar["date"].max())

Start date: 2011-01-29 00:00:00
End date: 2016-06-19 00:00:00

In [40]:
date_range = pd.date_range(
    start=calendar["date"].min(),
    end=calendar["date"].max(),
    freq="D"
)

missing_dates = date_range.difference(calendar["date"])

print("Missing dates:", len(missing_dates))

Missing dates: 0

In [41]:
calendar.isnull().sum()

date            0
wm_yr_wk        0
weekday         0
wday            0
month           0
year            0
d               0
event_name_1    0
event_type_1    0
event_name_2    0
event_type_2    0
snap_CA         0
snap_TX         0
snap_WI         0
week            0
day             0
dtype: int64

In [42]:
calendar.to_csv(
    "../data/processed/calendar_cleaned.csv",
    index=False
)

## Calendar Cleaning Summary

- Converted the date column to datetime format.
- Created year, month, week, day and weekday features.
- Checked the calendar date range and missing dates.
- Standardized missing event information as "No Event".
- Preserved the original calendar dataset in the raw folder.
- Saved the cleaned calendar dataset in the processed folder.

These calendar features will later be used for demand analysis and forecasting.