In [1]:
import pandas as pd

In [3]:
daily_sales = pd.read_csv(
    "../data/processed/daily_sales_sample.csv"
)

In [9]:
daily_sales.head()

,id,item,store,department,category,state_id,d,date,sales,event,event_type_1,event_name_2,event_type_2,weekday,month,year,week,day
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29

In [10]:
prices = pd.read_csv(
    "../data/raw/sell_prices.csv"
)

In [11]:
prices.head()

  store_id        item_id  wm_yr_wk  sell_price
0     CA_1  HOBBIES_1_001     11325        9.58
1     CA_1  HOBBIES_1_001     11326        9.58
2     CA_1  HOBBIES_1_001     11327        8.26
3     CA_1  HOBBIES_1_001     11328        8.26
4     CA_1  HOBBIES_1_001     11329        8.26

In [12]:
print("Price data shape:", prices.shape)

Price data shape: (6841121, 4)

In [13]:
print(prices.columns.tolist())

['store_id', 'item_id', 'wm_yr_wk', 'sell_price']

In [14]:
prices = prices.rename(
    columns={
        "item_id": "item",
        "store_id": "store",
        "sell_price": "price"
    }
)

In [15]:
prices.head()

  store           item  wm_yr_wk  price
0  CA_1  HOBBIES_1_001     11325   9.58
1  CA_1  HOBBIES_1_001     11326   9.58
2  CA_1  HOBBIES_1_001     11327   8.26
3  CA_1  HOBBIES_1_001     11328   8.26
4  CA_1  HOBBIES_1_001     11329   8.26

In [16]:
selected_items = daily_sales["item"].drop_duplicates().head(20).tolist()

In [17]:
selected_stores = daily_sales["store"].drop_duplicates().head(5).tolist()

In [18]:
print("Selected items:", selected_items)
print("Selected stores:", selected_stores)

Selected items: ['HOBBIES_1_001', 'HOBBIES_1_002', 'HOBBIES_1_003', 'HOBBIES_1_004', 'HOBBIES_1_005', 'HOBBIES_1_006', 'HOBBIES_1_007', 'HOBBIES_1_008', 'HOBBIES_1_009', 'HOBBIES_1_010', 'HOBBIES_1_011', 'HOBBIES_1_012', 'HOBBIES_1_013', 'HOBBIES_1_014', 'HOBBIES_1_015', 'HOBBIES_1_016', 'HOBBIES_1_017', 'HOBBIES_1_018', 'HOBBIES_1_019', 'HOBBIES_1_020']
Selected stores: ['CA_1']

In [19]:
daily_sales_subset = daily_sales[
    daily_sales["item"].isin(selected_items)
    & daily_sales["store"].isin(selected_stores)
].copy()

In [20]:
print(daily_sales_subset.shape)

(38260, 18)

In [21]:
prices_subset = prices[
    prices["item"].isin(selected_items)
    & prices["store"].isin(selected_stores)
].copy()

In [22]:
print(prices_subset.shape)

(4845, 4)

In [27]:
print("daily_sales columns:")
print(daily_sales.columns.tolist())

daily_sales columns:
['id', 'item', 'store', 'department', 'category', 'state_id', 'd', 'date', 'sales', 'event', 'event_type_1', 'event_name_2', 'event_type_2', 'weekday', 'month', 'year', 'week', 'day']

In [28]:
print("prices columns:")
print(prices.columns.tolist())

prices columns:
['store', 'item', 'wm_yr_wk', 'price']

In [29]:
calendar = pd.read_csv(
    "../data/processed/calendar_cleaned.csv"
)

In [30]:
daily_sales["date"] = pd.to_datetime(daily_sales["date"])
calendar["date"] = pd.to_datetime(calendar["date"])

In [31]:
daily_sales = daily_sales.merge(
    calendar[["date", "wm_yr_wk"]],
    on="date",
    how="left"
)

In [32]:
print(daily_sales.columns.tolist())

['id', 'item', 'store', 'department', 'category', 'state_id', 'd', 'date', 'sales', 'event', 'event_type_1', 'event_name_2', 'event_type_2', 'weekday', 'month', 'year', 'week', 'day', 'wm_yr_wk']

In [33]:
print(daily_sales["wm_yr_wk"].isnull().sum())

0

In [34]:
daily_sales_subset = daily_sales[
    daily_sales["item"].isin(selected_items)
    & daily_sales["store"].isin(selected_stores)
].copy()

prices_subset = prices[
    prices["item"].isin(selected_items)
    & prices["store"].isin(selected_stores)
].copy()

In [35]:
daily_sales_with_price = daily_sales_subset.merge(
    prices_subset,
    on=["item", "store", "wm_yr_wk"],
    how="left"
)

In [36]:
print(daily_sales["wm_yr_wk"].isnull().sum())
print(daily_sales_with_price.shape)

0
(38260, 20)

In [37]:
daily_sales_with_price.head()

,id,item,store,department,category,state_id,d,date,sales,event,event_type_1,event_name_2,event_type_2,weekday,month,year,week,day,wm_yr_wk,price
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29,11101,NaN
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29,11101,NaN
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29,11101,NaN
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29,11101,NaN
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,CA_1,HOBBIES_1,HOBBIES,CA,d_1,2011-01-29,0,No Event,No Event,No Event,No Event,Saturday,1,2011,4,29,11101,NaN

In [38]:
print(daily_sales_with_price.shape)

(38260, 20)

In [39]:
print("Missing prices:",
      daily_sales_with_price["price"].isnull().sum())

Missing prices: 5565

In [40]:
missing_price_pct = (
    daily_sales_with_price["price"].isnull().mean() * 100
)

print("Missing price percentage:",
      round(missing_price_pct, 2), "%")

Missing price percentage: 14.55 %

In [41]:
print(
    "Duplicate rows:",
    daily_sales_with_price.duplicated().sum()
)

Duplicate rows: 0

In [42]:
daily_sales_with_price["price"].describe()

count    32695.000000
mean         3.783135
std          3.539380
min          0.420000
25%          0.980000
50%          2.970000
75%          4.640000
max         12.680000
Name: price, dtype: float64

In [44]:
final_data = daily_sales_with_price[
    [
        "id",
        "item",
        "store",
        "department",
        "category",
        "state_id",
        "date",
        "sales",
        "price",
        "event",
        "event_type_1",
        "event_name_2",
        "event_type_2",
        "weekday",
        "year",
        "month",
        "week",
        "day",
        "wm_yr_wk"
    ]
].copy()

In [45]:
final_data.head()

,id,item,store,department,category,state_id,date,sales,price,event,event_type_1,event_name_2,event_type_2,weekday,year,month,week,day,wm_yr_wk
0,HOBBIES_1_001_CA_1_validation,HOBBIES_1_001,CA_1,HOBBIES_1,HOBBIES,CA,2011-01-29,0,NaN,No Event,No Event,No Event,No Event,Saturday,2011,1,4,29,11101
1,HOBBIES_1_002_CA_1_validation,HOBBIES_1_002,CA_1,HOBBIES_1,HOBBIES,CA,2011-01-29,0,NaN,No Event,No Event,No Event,No Event,Saturday,2011,1,4,29,11101
2,HOBBIES_1_003_CA_1_validation,HOBBIES_1_003,CA_1,HOBBIES_1,HOBBIES,CA,2011-01-29,0,NaN,No Event,No Event,No Event,No Event,Saturday,2011,1,4,29,11101
3,HOBBIES_1_004_CA_1_validation,HOBBIES_1_004,CA_1,HOBBIES_1,HOBBIES,CA,2011-01-29,0,NaN,No Event,No Event,No Event,No Event,Saturday,2011,1,4,29,11101
4,HOBBIES_1_005_CA_1_validation,HOBBIES_1_005,CA_1,HOBBIES_1,HOBBIES,CA,2011-01-29,0,NaN,No Event,No Event,No Event,No Event,Saturday,2011,1,4,29,11101

In [46]:
output_path = "../data/processed/daily_sales_with_price.csv"

final_data.to_csv(
    output_path,
    index=False
)

In [47]:
import os

file_size_mb = os.path.getsize(output_path) / (1024 * 1024)

print(f"File size: {file_size_mb:.2f} MB")

File size: 5.53 MB

In [48]:
print("Rows:", final_data.shape[0])
print("Columns:", final_data.shape[1])
print("Missing prices:", final_data["price"].isnull().sum())
print("Duplicates:", final_data.duplicated().sum())

Rows: 38260
Columns: 19
Missing prices: 5565
Duplicates: 0

## Price Integration Summary

- Integrated M5 weekly selling price information with the daily sales dataset.
- Used item, store and week (`wm_yr_wk`) as the merge keys.
- Checked missing price values and duplicate records.
- Created the final analytical dataset containing sales, price, product, store, date and event information.
- Used a selected M5 subset to keep the processed dataset below the project file-size limit.
- Saved the result as `daily_sales_with_price.csv`.